# Start from a Debian image with the latest version of Go installed
# and a workspace (GOPATH) configured at /go.
FROM golang

# Contact maintainer with any issues you encounter
MAINTAINER Richard Knop <risoknop@gmail.com>

# Set environment variables
ENV PATH /go/bin:$PATH

# Create a new unprivileged user
RUN useradd --user-group --shell /bin/false machinery

# Cd into the api code directory
WORKDIR /go/src/github.com/RichardKnop/machinery

# Copy the local package files to the container's workspace.
ADD . /go/src/github.com/RichardKnop/machinery

# Chown the application directory to the unprivileged user
RUN chown -R machinery:machinery /go/src/github.com/RichardKnop/machinery

# Use the unprivileged user
USER machinery

# Run integration tests as default command
CMD make test
